-- =============================================================================
-- Schema para Supabase - Leitor de Projetos Online Pro
-- Execute este script no SQL Editor do seu projeto Supabase
-- =============================================================================

-- 1. Tabela Histórico REC (Obras Orçadas e Arquivos .rec)
CREATE TABLE IF NOT EXISTS public.historico_rec (
    numero_obra TEXT PRIMARY KEY,
    dados_json TEXT NOT NULL,
    data_criacao TEXT NOT NULL,
    user_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela Obras (Projetos em edição salvos na tela de Resumo)
CREATE TABLE IF NOT EXISTS public.obras (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    data TEXT NOT NULL,
    dados_json TEXT NOT NULL,
    user_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela Projetos / Concessionárias (Ex: PARAIBA 027, RONDONIA 229)
CREATE TABLE IF NOT EXISTS public.projetos (
    nome TEXT PRIMARY KEY,
    codigo TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir projetos padrões se não existirem
INSERT INTO public.projetos (nome, codigo)
VALUES 
    ('PARAIBA', '027'),
    ('RONDONIA', '229')
ON CONFLICT (nome) DO NOTHING;

-- 4. Tabela Orçamento Mestre (Base de Preços e Fatores de Ativos)
CREATE TABLE IF NOT EXISTS public.tabela_orcamento_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo TEXT,
    desc_ativo TEXT,
    componente TEXT,
    projeto TEXT,
    mdo TEXT,
    codigo TEXT,
    desc_codigo TEXT,
    fator_i NUMERIC,
    fator_r NUMERIC,
    filtro TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela Usuários Nuvem (Controle de Acesso e Permissões)
CREATE TABLE IF NOT EXISTS public.usuarios_nuvem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    senha_hash TEXT NOT NULL,
    role TEXT DEFAULT 'operador',
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Índices para Otimização de Consultas
CREATE INDEX IF NOT EXISTS idx_historico_rec_user_id ON public.historico_rec(user_id);
CREATE INDEX IF NOT EXISTS idx_historico_rec_data ON public.historico_rec(data_criacao DESC);
CREATE INDEX IF NOT EXISTS idx_obras_user_id ON public.obras(user_id);
CREATE INDEX IF NOT EXISTS idx_tabela_master_codigo ON public.tabela_orcamento_master(codigo);
CREATE INDEX IF NOT EXISTS idx_tabela_master_ativo ON public.tabela_orcamento_master(ativo);

-- 7. Desabilitar RLS (Row Level Security) temporariamente ou permitir acesso pela API Key
ALTER TABLE public.historico_rec DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projetos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tabela_orcamento_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios_nuvem DISABLE ROW LEVEL SECURITY;
